# Generated by Django 5.0.6 on 2024-11-20 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("invoice_number", models.CharField(max_length=120, unique=True)),
                ("customer_name", models.CharField(max_length=120)),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Invoice_details",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=120)),
                ("quantity", models.PositiveBigIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.invoice",
                    ),
                ),
            ],
        ),
    ]
